---
version: 1

build_arg_defaults: 
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-20-early-access/ansible-builder-rhel8:2.0

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
